# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Programa
    url: "/#info"
    weight: 30

  - name: Merchandise
    url: "/#products"
    weight: 30

#  - name: Registo
#    url: "/#pretix"
#    weight: 40